apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOVEV4TVRneApPVFU0TkRWYUZ3MDBOVEV4TVRneE9UVTRORFZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEWnNRSVB5amVxREtGSDI3QURkbTZqU0N1NnQ0S2JUS0dMendPajNGRW1FK2dNR2FrNwo1NXZPemQrbVdlYXVQZjZvLytZMlF6QmR6Nmk2UFVlcVVIVU9tMlMvK3dsa3k0bS84R3Jqd0h4YXFBUXNSNjd1CjVhZ1E0bTd3QWI4ME9JYUpuOUhYTDh0WmR4QmFGWFBPZWxpbUM2UEl3TGlWdDJWQjZMck83R3ZXTXlGQ3QvN2IKM0RySDZ2NTN6cXBBRWV5SUliRWNveVRCQ0NPSjFxMUpZS0lIMFNoRnNzK1RtSHJyWk85cDU1cVMvQUxMNVcwMgpMdWVQMGNuMUxjMkxSeWlyYVRpcVoxOVhOYmxGRzFHcTdJNjdtNHlKVFZCZUVJUGh1MDVZY0ZHR1ZEb3EyNG5rCjhCckhIQ2toVnhsb2w2QzVFV0VyUStXTk01OUN5WU1XWlFCdkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlNkN1BRNitUWnhEWlJ4SXBmZgp3OVdTMkk2d1lqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFXMnAvUFFUYjVPNFJ2Qnp2MVVhcHNRcU00bi9oCmZXdlVFVlR4OFRtSW43QnRaa0dnSkVGSnRycEFEM3c3SVNBTzR3a1NpMWZLU2VhQXRkMERpVWwyK0FSaThmSzcKNWRVaXBsL2gvVFlxN2JHQmU1QzhrZzNiZDVSdDF3L3NQbDNDZytmdGIydjNITUZLY28zY3JqNm5NQmhKS3VlVgptQ3RBU1dCR2ZDOXdjRTR3a2lQZHo1eHBEcWhLQ0p3VWpzSUlaRW5xSUNjWXlqZ0xFRzlHd1Z5ZjN6RlN3RThvCkNyL3FZNUdYWVovdjR4UzFIaXVyZXNxS2JoSVZrNUZKOTltcjV2eXFOSkNKQ2FhZmY0anhISTVPU0s4UU9ONloKbG8zVGgwK05IdFEwczlPbVVWMThrbmhnZ29GdnBDbGlhUUFwMUpSTWpYdGgzVXU0aEQrOGRyamk2Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://9520b1c4-71cc-4ece-92fd-94815119dbe0.k8s.ondigitalocean.com
  name: do-sfo3-k8s-1-33-1-do-5-sfo3-1763495906297
contexts:
- context:
    cluster: do-sfo3-k8s-1-33-1-do-5-sfo3-1763495906297
    user: do-sfo3-k8s-1-33-1-do-5-sfo3-1763495906297-admin
  name: do-sfo3-k8s-1-33-1-do-5-sfo3-1763495906297
current-context: do-sfo3-k8s-1-33-1-do-5-sfo3-1763495906297
kind: Config
preferences: {}
users:
- name: do-sfo3-k8s-1-33-1-do-5-sfo3-1763495906297-admin
  user:
    token: dop_v1_909353d5c25104295429c71b72121e2e0b8bccdc316a4a7431f9989ea1fa5881
