apiVersion: v1
kind: Secret
metadata:
  name: pam-secrets
  namespace: pam
type: Opaque
stringData:
  # PostgreSQL
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "Pam9628#d"
  POSTGRES_DB: "pam"
  
  # Connection String para microservi√ßos
  DB_CONNECTION_STRING: "Host=postgres-service;Port=5432;Username=postgres;Password=Pam9628#d;Database=pam;"
  
  # RabbitMQ
  RABBITMQ_DEFAULT_USER: "admin"
  RABBITMQ_DEFAULT_PASS: "Pam9628#d"
  RABBITMQ_CONNECTION_STRING: "amqp://admin:Pam9628#d@rabbitmq-service:5672/"
  
  # Twilio
  TWILIO_ACCOUNT_SID: "ACe5cb2fffe4ef894ab63a275f8e431a75"
  TWILIO_AUTH_TOKEN: "d56135ec81910d78e9727c58cc6d39d5"
  TWILIO_PHONE_NUMBER: "+13853968548"
  
  # JWT
  JWT_SECRET: "7029e0dc-7c62-11eb-8cc1-cb436fe7eed0"
  JWT_ISSUER: "PAM_API"
  JWT_AUDIENCE: "PAM_Client"

  # Email Settings
  EMAIL_SMTP_HOST: "smtp.gmail.com"
  EMAIL_SMTP_PORT: "587"
  EMAIL_USERNAME: "No Reply - ESM"
  EMAIL_PASSWORD: "Qgexwmvnxhdjsyez"
  EMAIL_FROM: "developer.esmenezes@gmail.com"

  # Google API Key (para mapas)
  google-api-key: "YOUR_GOOGLE_API_KEY_HERE"

  # PagSeguro
  pagseguro-client-id: "YOUR_PAGSEGURO_CLIENT_ID_HERE"

