apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: pam
spec:
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Endpoints
metadata:
  name: postgres-service
  namespace: pam
subsets:
- addresses:
  - ip: 35.172.113.118
  ports:
  - port: 5432

